export { default as Dashboard } from './Dashboard'
export { default as Tarifs } from './Tarifs'
export { default as Historique } from './Historique'
export { default as Validation } from './Validation'
export { default as SubmitPayment } from './SubmitPayment'
export { default as StudentFinancialState } from './StudentFinancialState'
export { default as Exonerations } from './Exonerations'
export { default as Reports } from './Reports'